- name: Configure Doodler server on AWS EC2
  hosts: all
  become: true
  vars_files:
    - secrets.yml
  vars:
    github_repo: https://github.com/Saumya40-codes/Doodler
    app_directory: /home/ubuntu/doodler
    server_directory: "{{ app_directory }}/server"
    nodejs_port: 5000

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install nodejs, npm, nginx, certbot
      apt:
        name:
          - nodejs
          - npm
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Clone or update to latest project state of Github Repository
      git:
        repo: "{{ github_repo }}"
        dest: "{{ app_directory }}"
        version: master
        force: yes

    - name: Install server dependencies
      npm:
        path: "{{ server_directory }}"

    - name: Install PM2
      npm:
        name: pm2
        global: yes

    - name: Create .env file for the server
      copy:
        dest: "{{ server_directory }}/.env"
        content: |
          MONGODB_URI={{ MONGODB_URI }}

    - name: Start server with PM2 using npm start
      command: pm2 start npm --name doodler-server -- start
      args:
        chdir: "{{ server_directory }}"

    - name: Configure Nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify: Reload Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Reload Nginx

    - name: Obtain SSL certificate
      command: certbot --nginx -d {{ server_name }} --non-interactive --agree-tos -m saumyab5181@gmail.com

  handlers:
    - name: Reload Nginx
      systemd:
        name: nginx
        state: reloaded
