name: Run Ansible Configurations
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ansible-deploy.yml'
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Create Inventory File
        run: |
          echo "[servers]" > inventory
          echo "${{ secrets.EC2_PRIVATE_IP_1 }} ansible_ssh_user=ubuntu" >> inventory

      - name: Decrypt secrets file
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass
          ansible-vault decrypt ansible/secrets.yml --vault-password-file .vault_pass

      - name: Check EC2_PRIVATE_IP_1 secret
        run: |
          if [ -z "${{ secrets.EC2_PRIVATE_IP_1 }}" ]; then
            echo "EC2_PRIVATE_IP_1 secret is empty or not set"
            exit 1
          else
            echo "EC2_PRIVATE_IP_1 is set (value not shown for security reasons)"
          fi

      - name: Add SSH key
        run: |
          set -x
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519_temp
          chmod 600 ~/.ssh/id_ed25519_temp
          ssh-keygen -p -f ~/.ssh/id_ed25519_temp -m pem -N "" || echo "ssh-keygen failed"
          mv ~/.ssh/id_ed25519_temp ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ls -l ~/.ssh/id_ed25519
          if ! ssh-keyscan -H "${{ secrets.EC2_PRIVATE_IP_1 }}" >> ~/.ssh/known_hosts 2>&1; then
            echo "ssh-keyscan failed. Error output:"
            ssh-keyscan -H "${{ secrets.EC2_PRIVATE_IP_1 }}" 2>&1
            exit 1
          fi
          cat ~/.ssh/known_hosts
        shell: bash

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PRIVATE_IP_1 }} echo "SSH connection successful"

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory ansible/playbook.yml --vault-password-file .vault_pass

      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/id_ed25519 .vault_pass
