name: Run Ansible Configurations
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/run-ansible-configs.yml'
      - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Create Inventory File
        run: |
          echo "[servers]" > inventory
          echo "${{ secrets.EC2_PRIVATE_IP_1 }} ansible_ssh_user=ubuntu" >> inventory

      - name: Decrypt secrets file
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass
          ansible-vault decrypt ansible/secrets.yml --vault-password-file .vault_pass

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Test SSH connection
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PRIVATE_IP_1 }} echo "SSH connection successful"

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory ansible/playbook.yml --vault-password-file .vault_pass -e "ansible_ssh_private_key_file=~/.ssh/id_ed25519" -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"

      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/id_ed25519 .vault_pass
